#!/bin/sh

arg1=${1:-help}
arg2=${2:-day}

date=`date +%Y/%m/%d/%H:%M`
month=`date +%Y/%m`
day=`date +%d`

daily_repo_file="$HOME/.dri/daily/$month/$day.csv"
monthly_repo_file="$HOME/.dri/monthly/$month.csv"
header="When, Project, Category, What you did, How long"
if [ ! -e $daily_repo_file ]; then
  echo $header >> $daily_repo_file
fi

if [ ! -e $monthly_repo_file ]; then
  echo $header >> $monthly_repo_file
fi

main(){
  if [ $arg1 = "s" ]; then
    if [ $arg2 = "day" ]; then
      show_daily_repos
    elif [ $arg2 = "month" ]; then
      show_montly_repos
    else
      echo "unknown option"
    fi
  elif [ $arg1 = "w" ]; then
    write_repos
  elif [ $arg1 = "help" ]; then
    show_help
  else
    echo "unknown option"
  fi
}

show_help(){
  echo "dri - daily repos on cli "
  echo ""
  echo "(before run 'npm install tty-table')"
  echo ""
  echo ""
  echo "Commands:"
  echo ""
  echo "      s, s day  - show today's repo"
  echo "      s month   - show month's repo"
  echo "      w         - write new today's repo"
  echo ""
  echo ""
}

show_daily_repos(){
  head $daily_repo_file | tty-table
}

show_montly_repos(){
  head $monthly_repo_file | tty-table
}

write_repos(){

  mkdir -p "$HOME/.dri/$month"

  tmp_file="$HOME/.dri/$month/temp.txt"

  q1='# Project? \n'
  q2='# Category? { 0: development, 1: managing, 2: meeting, 3:others }\n'
  q3='# What you did?\n'
  q4='# How long?'
  questions=$q1$q2$q3$q4
  echo $questions > $tmp_file

  vim $tmp_file
  chmod 775 $tmp_file

  result="$date"
  count=0
  cat $tmp_file | while read line
  do
    if [[ $line != "#"* ]]; then
      case "$line" in
        0 ) result+="development" ;;
        1 ) result+="managing" ;;
        2 ) result+="meeting" ;;
        3 ) result+="others" ;;
        * ) result+=$line ;;
      esac
    else
      result+=", "
    fi

    count=`expr $count + 1`
    if [ $count -eq 8 ]; then
      echo $result >> $daily_repo_file
      echo $result >> $monthly_repo_file
    fi
  done

  rm $tmp_file
  echo "Success"
}

main
